api_key = "KC7SPM46W49HDFWL3PX4AP3PX"
feature = ["feelslikemax",
           "feelslikemin",
           "feelslike",
           "dew",
           "humidity",
           "precip",
           "precipprob",
           "precipcover",
           "preciptype",
           "snow",
           "snowdepth",
           "windgust",
           "windspeed",
           "winddir",
           "pressure",
           "cloudcover",
           "visibility",
           "solarradiation",
           "solarenergy",
           "uvindex",
           "moonphase",
           "conditions",
           "description",
           "icon",
           "stations"]
